using System;
using System.Collections.Generic;
using System.Text;
using System.Windows.Forms;

namespace TalentCalculator
{
    class Druid : ControlClass
    {
        public string GetTitles(Titles idx)
        {
            return TitleInfo[(int)idx];
        }
        public void claculateValue(PictureBox image, object sender, DrawComponents form, string value, PictureBox[] p)
        {
        }

        public int[] Fixed()
        {
            int[] array = new int[]
            {
                0,3,6,12,15,19,23,24,29,31,36,38,39,40,42,43,
                44,47,51,55,61,67,68,73,79,80,83,84,86,87,
                91,95,99,100,103,106,109,111,115,116,119,123,
                125,127,128,130,131
            };
            return array;
        }

        public int[] AbilityValue()
        {
            int[] array = new int[]
            {
                    5,5,3,2,2,3,3,1,2,5,
                    3,3,1,3,3,3,2,1,3,3,
                    3,5,3,1,1,2,3,1,
                    5,5,3,2,3,2,1,3,2,3,
                    2,2,2,1,2,3,5,3,1,2,
                    3,3,3,3,3,1,3,5,1,1,
                    2,3,5,5,3,3,3,1,2,5,
                    3,1,5,2,2,5,3,1,3,5,
                    3,3,1,3,2,5,1,
                };
            return array;
        }

        public int GetIndex(Ints idx)
        {
            return AbilityIndex[(int)idx];
        }

        private readonly static int[] AbilityIndex = 
        {
            0,
            28,
            58,
        };
        public string[] AbilityInfo()
        {
            string[] array = new string[]{
                "Starlight Wrath - \nReduces the cast time of your Wrath and Starfire spells by \n0.1 sec (1/5) \n0.2 sec (2/5) \n0.3 sec (3/5) \n0.4 sec (4/5) \n0.5 sec (5/5).",
                "Genesis - \nIncreases the damage and healing done by your periodic spell \ndamage and healing effects by \n1% (1/5) \n2% (2/5) \n3% (3/5) \n4% (4/5) \n5% (5/5).",
                "Moonglow - \nReduces the Mana cost of your Moonfire, Starfire, Starfall, Wrath, \nHealing Touch, Nourish, Regrowth and Rejuvenation spells by \n3% (1/3) \n6% (2/3) \n9% (3/3).",
                "Nature's Majesty - \nIncreases the critical strike chance of your Wrath, Starfire, \nStarfall, Nourish and Healing Touch spells by \n2% (1/2) \n4% (2/2).",
                "Improved Moonfire - \nIncreases the damage and critical strike \nchance of your Moonfire spell by \n5% (1/2) \n10% (2/2).",
                "Brambles - \nDamage from your Thorns and Entangling Roots increased by \n25% (1/3) \n50% (2/3) \n75% (3/3) \nand damage done by your Treants increased by \n5% (1/3) \n10% (2/3) \n15% (3/3). \nIn addition, damage from your Treants and attacks done to you \nwhile you have Barkskin active have a \n5% (1/3) \n10% (2/3) \n15% (3/3) \nchance to daze the target for 3 sec.",
                "Nature's Grace - \nAll non-periodic spell criticals have a \n33% (1/3) \n66% (2/3) \n100% (3/3) \nchance to grace you with a blessing of nature, \nincreasing your spell casting speed by 20% for 3 sec.",
                "Nature's Splendor - \nIncreases the duration of your Moonfire and Rejuvenation spells by 3 sec, \nyour Regrowth spell by 6 sec, and your Insect Swarm and Lifebloom spells by 2 sec.",
                "Nature's Reach - \nIncreases the range of your Balance spells and Faerie Fire (Feral) ability by \n10% (1/2) \n20% (2/2), \nand reduces the threat generated by your Balance spells by \n15% (1/2) \n30% (2/2).",
                "Vengeance - \nIncreases the critical strike damage bonus of your Starfire, \nStarfall, Moonfire, and Wrath spells by \n20% (1/5) \n40% (2/5) \n60% (3/5) \n80% (4/5) \n100% (5/5).",
                "Celestial Focus - \nReduces the pushback suffered from damaging attacks \nwhile casting Starfire, Hibernate and Hurricane by \n23% (1/3) \n46% (2/3) \n70% (3/3) \nand increases your total spell haste by \n1% (1/3) \n2% (2/3) \n3% (3/3).",
                "Lunar Guidance - \nIncreases your spell power by \n4% (1/3) \n8% (2/3) \n12% (3/3) \nof your total Intellect.",
                "Insect Swarm - \nThe enemy target is swarmed by insects, decreasing their \nchance to hit by 3% and causing 144 Nature damage over 12 sec.",
                "Improved Insect Swarm - \nIncreases your damage done by your \nWrath spell to targets afflicted by your Insect Swarm by \n1% (1/3) \n2% (2/3) \n3% (3/3), \nand increases the critical strike chance of your Starfire spell by \n1% (1/3) \n2% (2/3) \n3% (3/3) \non targets afflicted by your Moonfire spell.",
                "Dreamstate - \nRegenerate mana equal to \n4% (1/3) \n7% (2/3) \n7% (3/3) \nof your Intellect every 5 sec, even while casting.",
                "Moonfury - \nIncreases the damage done by your Starfire, Moonfire and Wrath spells by \n3% (1/3) \n6% (2/3) \n10% (3/3).",
                "Balance of Power - \nIncreases your chance to hit with all spells by \n2% (1/2) \n4% (2/2) \nand reduces your damage taken from all spells by \n3% (1/2) \n6% (2/2).",
                "Moonkin Form - \nShapeshift into Moonkin Form.  While in this form the armor \ncontribution from items is increased by 370%, damage taken while \nstunned is reduced by 15%, and all party and raid members within \n100 yards have their spell critical chance increased by 5%.  \nSingle target spell critical strikes in this form have a chance \nto instantly regenerate 2% of your total mana.  \nThe Moonkin can not cast healing or resurrection spells while shapeshifted. \n\nThe act of shapeshifting frees the caster of Polymorph and Movement Impairing effects.",
                "Improved Moonkin Form - \nYour Moonkin Aura also causes affected targets to gain \n1% (1/3) \n2% (2/3) \n3% (3/3) \nhaste and you to gain \n10% (1/3) \n20% (2/3) \n30% (3/3) \nof your spirit as additional spell damage.",
                "Improved Faerie Fire - \nYour Faerie Fire spell also increases the chance the target \nwill be hit by spell attacks by \n1% (1/3) \n2% (2/3) \n3% (3/3), \nand increases the critical strike chance of your damage spells by \n1% (1/3) \n2% (2/3) \n3% (3/3) \non targets afflicted by Faerie Fire.",
                "Owlkin Frenzy - \nAttacks done to you while in Moonkin form have a \n5% (1/3) \n10% (2/3) \n15% (3/3) \nchance to cause you to go into a Frenzy, increasing your damage by 10%, \ncause you to be immune to pushback while casting Balance spells and \nrestore 2% base mana every 2 sec. Lasts 10 sec.",
                "Wrath of Cenarius - \nYour Starfire spell gains an additional \n4% (1/5) \n8% (2/5) \n12% (3/5) \n16% (4/5) \n20% (5/5) \nand your Wrath gains an additional \n2% (1/5) \n4% (2/5) \n6% (3/5) \n8% (4/5) \n10% (5/5) \nof your bonus damage effects.",
                "Eclipse - \nWhen you critically hit with Starfire, you have a \n33% (1/3) \n66% (2/3) \n100% (3/3) \nchance of increasing damage done by Wrath by 40%. \nWhen you critically hit with Wrath, you have a \n20% (1/3) \n40% (2/3) \n60% (3/3) \nchance of increasing your critical strike chance with Starfire by 40%. \nEach effect lasts 15 sec and each has a separate 30 sec cooldown.  \nBoth effects cannot occur simultaneously.",
                "Typhoon - \nYou summon a violent Typhoon that does 400 Nature damage\n when in contact with hostile targets, knocking them \nback and dazing them for 6 sec.",
                "Force of Nature - \nSummons 3 treants to attack enemy targets for 30 sec.",
                "Gale Winds - \nIncreases damage done by your Hurricane and Typhoon spells by \n15% (1/2) \n30% (2/2), \nand increases the range of your Cyclone spell by \n2 yards (1/2) \n4 yards (2/2).",
                "Earth and Moon - \nYour Wrath and Starfire spells have a 100% chance \nto apply the Earth and Moon effect, which increases spell damage taken by \n2% (1/3) \n4% (2/3) \n6% (3/3) \nfor 12 sec.  \nAlso increases your spell damage by \n2% (1/3) \n4% (2/3) \n6% (3/3).",
                "Starfall - \nYou summon a flurry of stars from the sky on all targets within \n30 yards of the caster, each dealing 145 to 167 Arcane damage. \nAlso causes 26 Arcane damage to all other enemies within \n5 yards of the enemy target. \nMaximum 20 stars. \nLasts 10 sec.  \nShapeshifting into an animal form or mounting cancels the effect. \nAny effect which causes you to lose control of your \ncharacter will suppress the starfall effect.",
                "Ferocity - \nReduces the cost of your Maul, Swipe, Claw, \nRake and Mangle abilities by \n1 (1/5) \n2 (2/5) \n3 (3/5) \n4 (4/5) \n5 (5/5) \nRage or Energy.",
                "Feral Aggression - \nIncreases the attack power reduction of your Demoralizing Roar by \n8% (1/5) \n16% (2/5) \n24% (3/5) \n32% (4/5) \n40% (5/5) \nand the damage caused by your Ferocious Bite by \n3% (1/5) \n6% (2/5) \n9% (3/5) \n12% (4/5) \n15% (5/5).",
                "Feral Instinct - \nIncreases the damage done by your Swipe ability by \n10% (1/3) \n20% (2/3) \n30% (3/3) \nand reduces the chance enemies have to detect you while Prowling.",
                "Savage Fury - \nIncreases the damage caused by your Claw, Rake, Mangle (Cat), \nMangle (Bear), and Maul abilities by \n10% (1/2) \n20% (2/2).",
                "Thick Hide - \nIncreases your Armor contribution from cloth and leather items by \n4% (1/3) \n7% (2/3) \n10% (3/3).",
                "Feral Swiftness - \nIncreases your movement speed by \n15% (1/2) \n30% (2/2) \nin Cat Form and increases your chance to dodge \nwhile in Cat Form, Bear Form and Dire Bear Form by \n2% (1/2) \n4% (2/2).",
                "Survival Instincts - \nWhen activated, this ability temporarily grants you 30% of your \nmaximum health for 20 sec while in Bear Form, Cat Form, or Dire Bear Form.  \nAfter the effect expires, the health is lost.",
                "Sharpened Claws - \nIncreases your critical strike chance while in Bear, \nDire Bear or Cat Form by \n2% (1/3) \n4% (2/3) \n6% (3/3).",
                "Shredding Attacks - \nReduces the energy cost of your Shred ability by \n9 (1/2) \n18 (2/2) \nand the rage cost of your Lacerate ability by \n1 (1/2) \n2 (2/2).",
                "Predatory Strikes - \nIncreases your melee attack power in Cat, Bear and Dire Bear Forms by \n50% (1/3) \n100% (2/3) \n150% (3/3) \nof your level and \n7% (1/3) \n14% (2/3) \n20% (3/3) \nof any attack power on your equipped weapon.  \nIn addition, your finishing moves have a \n7% (1/3) \n13% (2/3) \n20% (3/3) \nchance per combo point to make your next Nature spell with a \nbase casting time less than 10 sec. \nbecome an instant cast spell.",
                "Primal Fury - \nGives you a \n50% (1/2) \n100% (2/2) \nchance to gain an additional 5 Rage anytime you get a critical strike while in Bear and \nDire Bear Form and your critical strikes from Cat Form abilities \nthat add combo points  have a \n50% (1/2) \n100% (2/2) \nchance to add an additional combo point.",
                "Primal Precision - \nIncreases your expertise by \n5 (1/2) \n10 (2/2), \nand you are refunded \n40% (1/2) \n80% (2/2) \nof the energy cost of a finishing move if it fails to land.",
                "Brutal Impact - \nIncreases the stun duration of your Bash and Pounce abilities by \n0.5 sec (1/2) \n1 sec (2/2) \nand decreases the cooldown of Bash by \n15 sec (1/2) \n30 sec (2/2).",
                "Feral Charge - \nTeaches Feral Charge (Bear) and Feral Charge (Cat). \nFeral Charge (Bear) - Causes you to charge an enemy, \nimmobilizing and interrupting any spell being cast for 4 sec. \nThis ability can be used in Bear Form and Dire Bear Form. \n15 second cooldown. \n\nFeral Charge (Cat) - Causes you to leap behind an enemy, \ndazing them for 3 sec. 30 second cooldown.",
                "Nurturing Instinct - \nIncreases your healing spells by up to \n35% (1/2) \n70% (2/2) \nof your Agility, and increases healing done to you by \n10% (1/2) \n20% (2/2) \nwhile in Cat form.",
                "Natural Reaction - \nIncreases your dodge while in Bear Form or Dire Bear Form by \n2% (1/3) \n4% (2/3) \n6% (3/3), \nand you regenerate \n1 (1/3) \n2 (2/3) \n3 (3/3) \nrage every time you dodge while in Bear Form or Dire Bear Form.",
                "Heart of the Wild - \nIncreases your Intellect by \n4% (1/5) \n8% (2/5) \n12% (3/5) \n16% (4/5) \n20% (5/5).  \nIn addition, while in Bear or Dire Bear Form your Stamina is increased by \n2% (1/5) \n4% (2/5) \n6% (3/5) \n8% (4/5) \n10% (5/5) \nand while in Cat Form your attack power is increased by \n2% (1/5) \n4% (2/5) \n6% (3/5) \n8% (4/5) \n10% (5/5).",
                "Survival of the Fittest - \nIncreases all attributes by \n2% (1/3) \n4% (2/3) \n6% (3/3), \nreduces the chance you'll be critically hit by melee attacks by \n2% (1/3) \n4% (2/3) \n6% (3/3), \nand increases your armor contribution from cloth \nand leather items in Bear Form and Dire Bear Form by \n11% (1/3) \n22% (2/3) \n33% (3/3).",
                "Leader of the Pack - \nWhile in Cat, Bear or Dire Bear Form, the Leader of the Pack increases \nranged and melee critical chance of all party and raid \nmembers within 100 yards by 5%.",
                "Improved Leader of the Pack - \nYour Leader of the Pack ability also causes affected targets to heal themselves for \n2% (1/2) \n4% (2/2) \nof their total health when they critically hit with a melee or ranged attack.  \nThe healing effect cannot occur more than once every 6 sec.  \nIn addition, you gain \n4% (1/2) \n8% (2/2) \nof your maximum mana when you benefit from this heal.",
                "Primal Tenacity - \nReduces the duration of fear effects by \n10% (1/3) \n20% (2/3) \n30% (3/3), \nreduces all damage taken while stunned by \n10% (1/3) \n20% (2/3) \n30% (3/3) \nwhile in Cat Form.",
                "Protector of the Pack - \nIncreases your attack power by \n2% (1/3) \n4% (2/3) \n6% (3/3) \nand reduces the damage you take by \n4% (1/3) \n8% (2/3) \n12% (3/3), \nwhile in Bear or Dire Bear Form.",
                "Predatory Instincts - \nWhile in Cat Form increases your damage from melee critical strikes by \n3% (1/3) \n7% (2/3) \n10% (3/3) \nand reduces the damage taken from area of effect attacks by \n10% (1/3) \n20% (2/3) \n30% (3/3).",
                "Infected Wounds - \nYour Shred, Maul, and Mangle attacks cause an Infected Wound in the target. \nThe Infected Wound reduces the movement speed of the target by \n16% (1/3) \n34% (2/3) \n50% (3/3) \nand the attack speed by \n6% (1/3) \n14% (2/3) \n20% (3/3). \nLasts 12 sec.",
                "King of the Jungle - \nWhile using your Enrage ability in Bear Form or Dire Bear Form, \nyour damage is increased by \n5% (1/3) \n10% (2/3) \n15% (3/3), \nand your Tiger's Fury ability also instantly restores \n20 (1/3) \n40 (2/3) \n60 (3/3) \nenergy.  \nIn addition, the mana cost of Bear Form, Cat Form, and Dire Bear Form \nis reduced by \n20% (1/3) \n40% (2/3) \n60% (3/3).",
                "Mangle - \nMangle the target, inflicting damage and causing the \ntarget to take additional damage from bleed effects for 1 min.  \nThis ability can be used in Cat Form or Dire Bear Form.",
                "Improved Mangle - \nReduces the cooldown of your Mangle (Bear) ability by \n0.5 sec (1/3) \n1.0 sec (2/3) \n1.5 sec (3/3), \nand reduces the energy cost of your Mangle (Cat) ability by \n2 (1/3) \n4 (2/3) \n6 (3/3).",
                "Rend and Tear - \nIncreases damage done by your Maul and \nShred attacks on bleeding targets by \n4% (1/5) \n8% (2/5) \n12% (3/5) \n16% (4/5) \n20% (5/5), \nand increases the critical strike chance of your \nFerocious Bite ability on bleeding targets by \n5% (1/5) \n10% (2/5) \n15% (3/5) \n20% (4/5) \n25% (5/5).",
                "Primal Gore - \nGrants the periodic damage from your Lacerate and Rip abilities the ability to critically hit.",
                "Berserk - \nWhen activated, this ability causes your Mangle (Bear) ability to hit up to \n3 targets and have no cooldown, and reduces the energy cost of \nall your Cat Form abilities by 50%.  Lasts 15 sec.  \nYou cannot use Tiger's Fury while Berserk is active. \n\nClears the effect of Fear and makes you immune to Fear for the duration.",
                "Improved Mark of the Wild - \nIncreases the effects of your Mark of \nthe Wild and Gift of the Wild spells by \n20% (1/2) \n40% (2/2), \nand increases all of your total attributes by \n1% (1/2) \n2% (2/2).",
                "Nature's Focus - \nReduces the pushback suffered from damaging attacks  while casting Healing Touch, \nWrath, Entangling Roots, Cyclone, Nourish, Regrowth and Tranquility by \n23% (1/3) \n46% (2/3) \n70% (3/3).",
                "Furor - \nGives you \n20% (1/5) \n40% (2/5) \n60% (3/5) \n80% (4/5) \n100% (5/5) \nchance to gain 10 Rage when you shapeshift into \nBear and Dire Bear Form, and you keep up to \n20 (1/5) \n40 (2/5) \n60 (3/5) \n80 (4/5) \n100 (5/5) \nof your Energy when you shapeshift into Cat Form, \nand increases your total Intellect while in Moonkin form by \n2% (1/5) \n4% (2/5) \n6% (3/5) \n8% (4/5) \n10% (5/5).",
                "Naturalist - \nReduces the cast time of your Healing Touch spell by \n0.1 sec (1/5) \n0.2 sec (2/5) \n0.3 sec (3/5) \n0.4 sec (4/5) \n0.5 sec (5/5) \nand increases the damage you deal with physical attacks in all forms by \n2% (1/5) \n4% (2/5) \n6% (3/5) \n8% (4/5) \n10% (5/5).",
                "Subtlety - \nReduces the threat generated by your restoration spells by \n10% (1/3) \n20% (2/3) \n30% (3/3) \nand reduces the chance your helpful spells, \nMoonfire, and Insect Swarm will be dispelled by \n10% (1/3) \n20% (2/3) \n30% (3/3).",
                "Natural Shapeshifter - \nReduces the mana cost of all shapeshifting by \n10% (1/3) \n20% (2/3) \n30% (3/3).",
                "Intensity - \nAllows \n17% (1/3) \n33% (2/3) \n50% (3/3) \nof your Mana regeneration to continue while casting \nand causes your Enrage ability to instantly generate \n4 rage (1/3) \n7 rage (2/3) \n10 rage (3/3).",
                "Omen of Clarity - \nEach of the Druid's damage, healing spells and auto attacks \nhas a chance of causing the caster to enter a Clearcasting state.  \nThe Clearcasting state reduces the Mana, Rage or Energy \ncost of your next damage, healing spell or offensive ability by 100%.",
                "Master Shapeshifter - \nGrants an effect which lasts while the Druid is within the \nrespective shapeshift form. \n\nBear Form - Increases physical damage by \n2% (1/2) \n4% (2/2). \n\nCat Form - Increases critical strike chance by \n2% (1/2) \n4% (2/2). \n\nMoonkin Form - Increases spell damage by \n2% (1/2) \n4% (2/2). \n\nTree of Life Form - Increases healing by \n2% (1/2) \n4% (2/2).",
                "Tranquil Spirit - \nReduces the mana cost of your Healing Touch, Nourish and Tranquility spells by \n2% (1/5) \n4% (2/5) \n6% (3/5) \n8% (4/5) \n10% (5/5).",
                "Improved Rejuvenation - \nIncreases the effect of your Rejuvenation spell by \n5% (1/3) \n10% (2/3) \n15% (3/3).",
                "Nature's Swiftness - \nWhen activated, your next Nature spell with a base \ncasting time less than 10 sec. becomes an instant cast spell.",
                "Gift of Nature - \nIncreases the effect of all healing spells by \n2% (1/5) \n4% (2/5) \n6% (3/5) \n8% (4/5) \n10% (5/5).",
                "Improved Tranquility - \nReduces threat caused by Tranquility by \n50% (1/2) \n100% (2/2), \nand reduces the cooldown by \n30% (1/2) \n60% (2/2).",
                "Empowered Touch - \nYour Healing Touch spell gains an additional \n20% (1/2) \n40% (2/2) \nand your Nourish spell gains an additional \n10% (1/2) \n20% (2/2) \nof your bonus healing effects.",
                "Nature's Bounty - \nIncreases the critical effect chance of your Regrowth and Nourish spells by \n5% (1/5) \n10% (2/5) \n15% (3/5) \n20% (4/5) \n25% (5/5).",
                "Living Spirit - \nIncreases your total Spirit by \n5% (1/3) \n10% (2/3) \n15% (3/3).",
                "Swiftmend - \nConsumes a Rejuvenation or Regrowth effect on a friendly target to \ninstantly heal them an amount equal to 12 sec of \nRejuvenation or 18 sec. of Regrowth.",
                "Natural Perfection - \nYour critical strike chance with all spells is increased by \n1% (1/3) \n2% (2/3) \n3% (3/3) \nand critical strikes against you give you the \nNatural Perfection effect reducing all damage taken by \n2% (1/3) \n3% (2/3) \n4% (3/3).  \nStacks up to 3 times.  Lasts 8 sec.",
                "Empowered Rejuvenation - \nThe bonus healing effects of your healing over time spells is increased by \n4% (1/5) \n8% (2/5) \n12% (3/5) \n16% (4/5) \n20% (5/5).",
                "Living Seed - \nWhen you critically heal your target with Swiftmend, \nRegrowth, Nourish or Healing Touch spell you have a \n33% (1/3) \n66% (2/3) \n100% (3/3) \nchance to plant a Living Seed on the target \nfor 30% of the amount healed. \nThe Living Seed will bloom when \nthe target is next attacked. Lasts 15 sec.",
                "Revitalize - \nYour Rejuvenation and Wild Growth spells have a \n5% (1/3) \n10% (2/3) \n15% (3/3) \nchance to restore 8 Energy, 4 Rage, \n1% Mana or 16 Runic Power per tick.",
                "Tree of Life - \nReduces the mana cost of your healing over time spells \nby 20% and grants the ability to shapeshift into the Tree of Life. \nWhile in this form you increase healing received by \n6% for all party and raid members within 100 yards, \nand you can only cast Restoration spells in addition to Innervate, \nBarkskin, Nature's Grasp and Thorns spells.\n\nThe act of shapeshifting frees the caster of Polymorph and Movement Impairing effects.",
                "Improved Tree of Life - \nIncreases your armor contribution from \nitems while in Tree of Life Form by \n67% (1/3) \n133% (2/3) \n200% (3/3), \nand increases your healing spell power by \n5% (1/3) \n10% (2/3) \n15% (3/3) \nof your spirit while in Tree of Life Form.",
                "Improved Barkskin - \nGrants \n80% (1/2) \n160% (2/2) \nadditional armor contribution from cloth and \nleather items while in Travel Form or while not shapeshifted, \nincreases the damage reduction granted by your Barkskin spell by \n5% (1/2) \n10% (2/2) \nand reduces the chance your Barkskin is dispelled by \n35% (1/2) \n70% (2/2).",
                "Gift of the Earthmother - \nIncreases your total spell haste by \n2% (1/5) \n4% (2/5) \n6% (3/5) \n8% (4/5) \n10% (5/5) \nand reduces the base cooldown of your Lifebloom spell by \n2% (1/5) \n4% (2/5) \n6% (3/5) \n8% (4/5) \n10% (5/5).",
                "Wild Growth - \nHeals up to 5 friendly party or raid members within 15 yards of \nthe target for 686 over 7 sec. \nThe amount healed is applied quickly at first, \nand slows down as the Wild Growth reaches its full duration.",
            };
            return array;
        }
        private readonly static string[] TitleInfo = 
        {
            "Balance",
            "Feral Combat",
            "Restoration",
        };
    }
}